version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "6544:5432"
    env_file:
      - .env

    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
